### PR TITLE
Unknown charge state full

### PR DESCRIPTION
**Pull request by cmd-johnson**
```
unknown charge status: full in/home/steel/.atom/packages/battery-status/lib/battery-status-view.coffee:79
```

^ the trace says it all

### CODE REVIEW

**Comment by cmd-johnson** [comment]
Well, I never caught that value, should be fixed now.

**Comment by steelbrain** [comment]
wait, did I open this bug as a PR? Is it a bug in GitHub or did I actually open this bug report as a PR?

**Comment by cmd-johnson** [comment]
Hah, no, that was my fault, I just tried the `hub` command line untility and somehow managed to get your bug report converted to an issue.

**Comment by steelbrain** [comment]
@cmd-johnson would you mind posting the hub commands that led you to this output? I am curious as I use hub everyday and don't know about this.

**Comment by cmd-johnson** [comment]
I believe it was `hub pull-request -i [issue-number]`.
Hower the command printed that this usage was deprecated.

**Pull request merged**
